version: '3.8'

networks:
  aurabank-gateway-net:
    driver: bridge

services:
  # --- Core Microservices ---
  auth-service:
    image: rafat04/aurabank-auth-service:latest
    container_name: aurabank-auth-service
    ports:
      - "8000:8000"
    networks:
      - aurabank-gateway-net
    restart: unless-stopped

  accounts-service:
    image: rafat04/aurabank-accounts-service:latest
    container_name: aurabank-accounts-service
    ports:
      - "8001:8001"
    networks:
      - aurabank-gateway-net
    restart: unless-stopped

  transactions-service:
    image: rafat04/aurabank-transactions-service:latest
    container_name: aurabank-transactions-service
    ports:
      - "8002:8002"
    networks:
      - aurabank-gateway-net
    restart: unless-stopped

  # --- Monitoring Stack ---
  prometheus:
    image: prom/prometheus:latest
    container_name: aurabank-prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - aurabank-gateway-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: aurabank-grafana
    ports:
      - "3000:3000"
    networks:
      - aurabank-gateway-net
    restart: unless-stopped